<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.12" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.22.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ProjetoBancario.Dados\ProjetoBancario.Dados.csproj" />
    <ProjectReference Include="..\ProjetoBancario.Dominio\ProjetoBancario.Dominio.csproj" />
    <ProjectReference Include="..\ProjetoBancario.DTOs\ProjetoBancario.DTOs.csproj" />
  </ItemGroup>

</Project>
