<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ProjetoBancario.Dados\ProjetoBancario.Dados.csproj" />
    <ProjectReference Include="..\ProjetoBancario.Dominio\ProjetoBancario.Dominio.csproj" />
  </ItemGroup>

</Project>
